# Generated by Django 2.2.8 on 2020-02-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNo', models.CharField(max_length=100)),
                ('Section_No', models.CharField(max_length=10)),
                ('Description', models.TextField()),
            ],
        ),
    ]
