# Generated by Django 2.2.8 on 2020-02-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Police', '0003_remove_crime_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Victim_Name', models.CharField(max_length=100)),
                ('Complaint', models.TextField()),
                ('Aaadhar_No', models.IntegerField()),
                ('Contact_No', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('Chowki', models.TextField()),
                ('User_Verified', models.BooleanField(default=False)),
                ('Police_Verified', models.BooleanField(default=False)),
            ],
        ),
    ]
